version: '3.9'

services:
  db:
    image: postgres:16
    container_name: pokemon_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pokemon
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pokemon"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:
